### ISSUE TITLE
关于包的版本兼容性问题

### ISSUE THREAD

**Issue by XeroAlpha** [mcpews/MyAgent#2]
您应当在ReadMe或者packages.json中提到需要的ws模块的版本。最新版本的ws不一定与您当前使用的版本兼容，这可能引起bug。
您可以在安装ws模块时加上-P选项来自动在packages.json中加入该依赖。

**Comment by XeroAlpha** [comment]
ws模块仍然在更新，因此完全存在未来版本不兼容于现在版本的可能（5.2.2）。建议在ReadMe或者packages.json中加入兼容版本。

[Github ws](https://github.com/websockets/ws)

**Comment by LNSSPsd** [comment]
OK.
